### ISSUE TITLE
Svg files not copied

### ISSUE THREAD

**Issue by ofriedrich** [helios-ag/elfinder-component#15]
SVG files should also be part of the files section in _composer.json_. Otherwise they are not copied during _composer install_

```
            "files": [
                "dist/img/*.svg",
                "dist/img/*.png",
                "dist/img/*.gif",
                "dist/js/i18n/*.js"
            ]
```

https://github.com/helios-ag/elfinder-component/blob/88d12a1e9f47f437e7bbf2f1e0bb0eaa2e84dbe4/composer.json#L32

**Comment by helios-ag** [comment]
Was resolved in [3.1.1](https://github.com/helios-ag/elfinder-component/tree/3.1.1)
