### ISSUE TITLE
Critical update needed

### ISSUE THREAD

**Issue by zorn-v** [helios-ag/elfinder-component#17]
As noticed here https://github.com/Studio-42/elFinder

> WARNING: IF YOU HAVE OLDER (IN PARTICULAR 2.1.45 OR EARLIER) VERSIONS OF ELFINDER ON PUBLIC SERVERS, IT MAY CAUSE SERIOUS DAMAGE TO YOUR SERVER AND VISITED USER. YOU SHOULD UPDATE TO THE LATEST VERSION OR REMOVE IT FROM THE SERVER.

Version in this package is 2.1.42

**Comment by helios-ag** [comment]
Well, bundle itself depends on elfinder php library, so technically it only require to update dependencies. 
Here we store only frontend related stuff (js/assets, etc) just for simplified intstallion of elfinder.
Anyway thanks for reporting, elfinder-component updated :)
