### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by ghost** [helios-ag/elfinder-component#9]
components/jqueryui was updated to 1.12  which prevents install.

**Comment by timothymctim** [comment]
Is there a reason why to require ` "components/jquery": "^1.8"` instead of something more recent (e.g., `^3.2`)?

**Comment by helios-ag** [comment]
Well i think we can use less strict coinstraints, something like >=1.8

**Comment by timothymctim** [comment]
Something like that would be great! I would be conservative with `>=` and maybe use something like `>=1.8 <4.0` instead. but I'm not so good with [composer's versioning](https://getcomposer.org/doc/articles/versions.md).

**Comment by helios-ag** [comment]
Tagged as 2.2, you can update deps to obtain most recent versions of component and related jQuery libs.
